import services as s
from time import sleep
aha = s.get_user_by_username("ahafshin")
mhk = s.get_user_by_username("mhk488")
nmf = s.get_user_by_username("normalguy")
ili = s.get_user_by_username("iigames")
s.new_post(aha.userID, "10")
s.new_post(aha.userID, "11")
s.new_post(aha.userID, "12")
s.new_post(aha.userID, "13")
s.new_post(aha.userID, "14")
s.new_post(mhk.userID, "20")
s.new_post(mhk.userID, "21")
s.new_post(mhk.userID, "22")
s.new_post(mhk.userID, "23")
s.new_post(mhk.userID, "24")
s.new_post(nmf.userID, "30")
s.new_post(nmf.userID, "31")
s.new_post(nmf.userID, "32")
s.new_post(nmf.userID, "33")
s.new_post(nmf.userID, "34")
s.new_post(ili.userID, "40")
s.new_post(ili.userID, "41")
s.new_post(ili.userID, "42")
s.new_post(ili.userID, "43")
s.new_post(ili.userID, "44")
print("done")
sleep(60)
s.new_post(aha.userID, "15")
s.new_post(aha.userID, "16")
s.new_post(aha.userID, "17")
s.new_post(aha.userID, "18")
s.new_post(aha.userID, "19")
s.new_post(mhk.userID, "25")
s.new_post(mhk.userID, "26")
s.new_post(mhk.userID, "27")
s.new_post(mhk.userID, "28")
s.new_post(mhk.userID, "29")
s.new_post(nmf.userID, "35")
s.new_post(nmf.userID, "36")
s.new_post(nmf.userID, "37")
s.new_post(nmf.userID, "38")
s.new_post(nmf.userID, "39")
s.new_post(ili.userID, "45")
s.new_post(ili.userID, "46")
s.new_post(ili.userID, "47")
s.new_post(ili.userID, "48")
s.new_post(ili.userID, "49")
print("done")
sleep(50)
s.new_post(mhk.userID, "x1")